In [1]:
import numpy as np

In [2]:
a=np.arange(15).reshape(3,5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a. itemsize

4

In [7]:
a.dtype.name

'int32'

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [10]:
b=np.array([6,7,8])

In [11]:
b

array([6, 7, 8])

In [12]:
type(b)

numpy.ndarray

In [1]:
a = np. array(2,3,4)

NameError: name 'np' is not defined

In [2]:
a = np. array([2,3,4])

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [4]:
a = np. array(2,3,4)

ValueError: only 2 non-keyword arguments accepted

In [5]:
a = np.array([2,3,4])

In [6]:
a

array([2, 3, 4])

In [7]:
a.dtype

dtype('int32')

In [8]:
b = np.array([1.2,3.5,5.1])

In [9]:
b.dtype

dtype('float64')

In [10]:
b = np.array([(1.5,2,3),(4,5,6)])

In [11]:
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [12]:
c = np.array([[1,2], [3,4]], dtype=complex)

In [13]:
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [14]:
np. zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [15]:
np.ones((2,3,4))

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [16]:
np.empty((2,3))

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [17]:
np.arrange(10,30,5)

AttributeError: module 'numpy' has no attribute 'arrange'

In [18]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [19]:
np.arange(0,2,0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [20]:
from numpy import pi

In [21]:
nplinspace(0,2,9)

NameError: name 'nplinspace' is not defined

In [22]:
np.linspace(0,2,9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [23]:
x = np.linspace(0,2*pi,100)

In [24]:
f = np.sin(x)