In [1]:
import numpy as np

In [2]:
a = np.arrange(15). reshape(3, 5)

AttributeError: module 'numpy' has no attribute 'arrange'

In [3]:
a = np.arange(15). reshape(3,5
                        )

In [4]:
a = np.arange(15). reshape(3,5)

In [5]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
a.ndim

2

In [7]:
a.shape

(3, 5)

In [8]:
a.dtype.name

'int32'

In [9]:
a.itemsize

4

In [10]:
type(a)

numpy.ndarray

In [11]:
b = np.array([6, 7, 8])

In [12]:
b

array([6, 7, 8])

In [13]:
type(b)

numpy.ndarray

In [14]:
import numpy as np

In [15]:
a = np. array([2,3,4])

In [16]:
a

array([2, 3, 4])

In [17]:
a.dtype

dtype('int32')

In [18]:
b=np.array([1.2,3.5,5.1])

In [19]:
b

array([ 1.2,  3.5,  5.1])

In [20]:
b.dtype

dtype('float64')

In [21]:
b = np.array([(1.5,2,3), (4,5,6)])

In [22]:
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [23]:
a.dtype

dtype('int32')

In [24]:
c = np.array([1,2], [3,4], dtype=complex)

TypeError: Argument given by name ('dtype') and position (2)

In [25]:
np.array([[1,2],[3,4]], dtype=complex)

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [26]:
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [27]:
a

array([2, 3, 4])

In [28]:
aa

NameError: name 'aa' is not defined

In [29]:
a

array([2, 3, 4])

In [30]:
np.zeros(3,4)

TypeError: data type not understood

In [31]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [32]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [33]:
np.empty((2,3))

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [34]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [35]:
np.arange(0,2,0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [36]:
np.arange(10,30,5)


array([10, 15, 20, 25])

In [37]:
np.arange(0,2,0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [38]:
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [39]:
np.arange(10,100,0)

ZeroDivisionError: division by zero

In [40]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np,arange(0,10)

NameError: name 'arange' is not defined

In [43]:
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(-10,10)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [45]:
np.arange(-10,10,-5)

array([], dtype=int32)

In [46]:
from numpy import pi

In [47]:
np.linspace(0,2,9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [48]:
x=np.linspace(0,2*pi,100)

In [49]:
f=np.sin(X)

NameError: name 'X' is not defined

In [50]:
f=np.sin(x)

In [51]:
a=np.arange(6)

In [52]:
print(a)

[0 1 2 3 4 5]


In [53]:
b=np.arange(12).reshape(4,3)

In [54]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [55]:
c = np.arange(24).reshape(2,3,4)

In [56]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [57]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [58]:
print(np.arange(10000))

[   0    1    2 ..., 9997 9998 9999]


In [59]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


In [60]:
print(np.arange(20))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [61]:
print(np.arange(20.2))

[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.]


In [62]:
print(np.arange(20,2))

[]


In [63]:
print(np.arange(20).reshape(10))

ValueError: cannot reshape array of size 20 into shape (10,)

In [64]:
print(np.arange(20).reshape(10,2))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [65]:
a=np.arange(20)

In [66]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [67]:
print(a.reshape(2,10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [68]:
print(a.reshape(2,2,5))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [69]:
print(a.reshape(5,2,2))

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [70]:
a= np.array([20,30,40,50])

In [71]:
b=np.arange(4)

In [72]:
b

array([0, 1, 2, 3])

In [73]:
c=a-b

In [74]:
c

array([20, 29, 38, 47])

In [75]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [76]:
b*2

array([0, 2, 4, 6])

In [77]:
b***2

SyntaxError: invalid syntax (<ipython-input-77-0343165b6663>, line 1)

In [78]:
b^2

array([2, 3, 0, 1], dtype=int32)

In [79]:
a<35

array([ True,  True, False, False], dtype=bool)

In [80]:
print(a<35)

[ True  True False False]


In [81]:
a=np.array([[1,1],
            ...[0,1]])

TypeError: 'ellipsis' object is not subscriptable

In [82]:
A=np.array([[1,1],
...        [0,1]])

In [83]:
b=np.array([[2,0],])

In [84]:
B=np.array([[2,0],
...     [3,4]])

In [85]:
A*B

array([[2, 0],
       [0, 4]])

In [86]:
A.dot(b)

ValueError: shapes (2,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

In [87]:
int(x)

TypeError: only length-1 arrays can be converted to Python scalars